plugins {
    id "fabric-loom" version "1.14-SNAPSHOT"
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

repositories {
    maven { url "https://repo.greenhouse.house/releases/" }
    // maven { url "https://mvn.devos.one/releases/" } // Porting Lib
    maven { url "https://repo.greenhouse.house/snapshots/" } // Temporary Porting Lib Fork for 1.21
    maven {
        url "https://jitpack.io/" // Fabric ASM
        content {
            excludeGroup "io.github.fabricators_of_create"
        }
    }
    maven { url "https://api.modrinth.com/maven" }
}

fabricApi {
    configureDataGeneration() {
        client = true
    }
}

dependencies {
    minecraft "com.mojang:minecraft:$minecraft_version"
    mappings "net.fabricmc:yarn:$yarn_mappings:v2"
    modImplementation "net.fabricmc:fabric-loader:$loader_version"

    modImplementation "net.fabricmc.fabric-api:fabric-api:$fabric_version"

    modImplementation("vectorwing:FarmersDelight:$fdrf_version") {
        exclude(group: "net.fabricmc")
    }
}

processResources {
    var replaceProperties = [
            minecraft_min_version: minecraft_min_version,
            minecraft_max_version: minecraft_max_version,
            loader_version       : loader_version,

            mod_id               : mod_id,
            mod_name             : mod_name,
            mod_version          : version,
            mod_license          : mod_license,
            mod_authors          : mod_authors,
            mod_description      : mod_description,
            mod_credits          : mod_credits,
            mod_homepage         : mod_homepage,
            mod_github           : mod_github,
            fdrf_version         : fdrf_version
    ]
    // setting them as input
    inputs.properties replaceProperties

    filesMatching("fabric.mod.json") {
        expand replaceProperties + [project: project]
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

tasks.withType(Copy).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

tasks.withType(Jar).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}" }
    }
}