# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
minecraft_version=1.21.10
minecraft_min_version=1.21.9
minecraft_max_version=1.21.10
yarn_mappings=1.21.9+build.1
loader_version=0.18.3

# Mod Properties
mod_id=corndelight
mod_name=Corn Delight
mod_version=1.21.10-1.0.0
mod_license=MIT License
mod_group_id=krelox
mod_authors=KreloX
mod_description=An a-maize-ing Farmer's Delight addon! Rewrite of Corn Delight for Fabric and Quilt
mod_homepage=https://modrinth.com/mod/corn-delight-fabric
mod_github=https://github.com/KreloX/CornDelight
mod_credits=sz0999312, yuriscat

# Dependency Properties
fabric_version=0.134.1+1.21.9
fdrf_version=1.21.10-3.3.3+refabricated
